### ISSUE TITLE
Add Class::Func info to all Loggers

### ISSUE THREAD

**Issue by Dante-666** [Dante-666/random-wallpaper#43]

**Comment by Dante-666** [comment]
This seems to be a useful utility to figure out where the problem is by reading the logs.

**Comment by PracticalMetal** [comment]
Hi, i would like to work on this, can you suggest me ways to get started?

**Comment by Dante-666** [comment]
Hi Pulkit, thank you for showing interest. There are methods in the compiler, for gcc, it's _PRETTYFUNC_ which gives too much info and you'd have to replace log calls with a #define statement and use regular expressions to trim the prettyfunc data.
Which OS are you working on?

**Comment by PracticalMetal** [comment]
Linux

**Comment by Dante-666** [comment]
Cool, give it a try. It's too basic. Make sure to add this conditionally only for Linux and GCC

**Comment by PracticalMetal** [comment]
Okay! I am on it, can you please assign me?

**Comment by Dante-666** [comment]
Hi Pulkit, how is it going, do you need some help?

**Comment by PracticalMetal** [comment]
Hi, I wanted to know what do you mean when you say "add" info to that class, should I store the string in a variable or display it on the console? Please let me know

**Comment by Dante-666** [comment]
Let's say there is a class

```
#include "logger.h"

class X {
public:
void foo() {
Logger::LogDebug("message");
}
void foo2() {
Logger::LogDebug("message2");
}
};
```

In the logs, it should show that "message" came from X::foo
<time> [DEBUG] [X::foo] : "message"
<time> [DEBUG] [X::foo2] : "message2"

For GCC, if you call `__PRETTYFUNC__` gives this information when called inside the function, you just have to figure out how to put it in. I'm thinking #define statements will get you there. Let me know if you need more info.

**Comment by Dante-666** [comment]
Right now, there's only a ConsoleLogger, but the design allows configuring other loggers as well but for this application, a FileLogger is the max you would need.

https://github.com/Dante-666/random-wallpaper/blob/fa933e035ca258fb540340234e061a226bbe8a77/src/logutil/logger.cc#L28

The main method which generates the string and hands it over to loggerImpls need this modification.
